export var cleaner={
    "Family Dollar": {
        "sorted_by_score": [
            {
                "product_rating": "Not Found",
                "distance": "15.7 miles",
                "badge": "None",
                "stock_information": "In Stock",
                "status": "unprocessed",
                "store_address": "1227 E Grove Ave, Rantoul",
                "hours": "Today: 9:00 AM - 10:00 PM",
                "product_id": "7dd7cab1-2a21-4827-9511-a49daf228491",
                "discount": -1.0,
                "old_price": -1.0,
                "value_per_unit": "$0.098/oz",
                "extracted_availability": true,
                "positive_reviews": [],
                "delivery_options": "Not Found",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTNjX_zRHExmilVWhxuMnpRHFjvrogglT-Hil1Ii5CIj6znmPxAkrmpQxsUpZnIut1D6_1EAF3r0mCdD0U9WZblSrVVywOR9LsPmImv1Zw&usqp=CAE",
                "negative_reviews": [],
                "extensions": [],
                "store_rating": -1.0,
                "store_reviews": -1.0,
                "product_hash": "8091291142b0a3071a63e154f82000b27f72520a142924633188b5b853958452",
                "extracted_price": 2.75,
                "reasons_not_to_buy": [
                    "No savings or promotional offers mentioned",
                    "No information about certifications or listings"
                ],
                "product_amount": "28 fl oz",
                "link": "https://www.google.com/shopping/product/9581373145482938617?hl&prds=oid:11091789336316009600,pid:766997163069631063&sts=2&lsf=seller:253032654,store:10849949268498103315,s:h",
                "tag": "None",
                "description": "Removes soils with ease. Provides protection against stains in sinks and toilets. Formula leaves a fresh scent.",
                "extracted_product_reviews": -1.0,
                "price": 2.75,
                "product_reviews": "Not Found",
                "reasons_to_buy": [
                    "Effective in removing soils and stains",
                    "Leaves a fresh scent"
                ],
                "extracted_product_rating": -1.0,
                "store": "Family Dollar",
                "title": "Mr. Clean Antibacterial Multi-Surface Cleaner, Summer Citrus - 28 oz",
                "score": 0.827153683
            },
            {
                "product_rating": 4.8,
                "distance": 15.7,
                "badge": "None",
                "stock_information": "15.7 mi \\u00b7 In stock \\u00b7 Free 30-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "hours": "Not Found",
                "product_id": "0613eaa5-46d3-4e16-8eac-533370851be9",
                "discount": -1.0,
                "old_price": -1.0,
                "value_per_unit": "$0.09/fl oz",
                "extracted_availability": false,
                "positive_reviews": [],
                "delivery_options": "15.7 mi \\u00b7 In stock \\u00b7 Free 30-day returns",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRdJOdGmJGhWxWvG7b4a07LeOlrquhXt0H1VHAiyWanmE8360tCrwnHEVVsaj5VDesMEK2Gxaze&usqp=CAE",
                "negative_reviews": [],
                "extensions": [
                    "Concentrate"
                ],
                "store_rating": -1.0,
                "store_reviews": -1.0,
                "product_hash": "9a3755d33425e00cbbf6c9c41a5993a5ab89c27c8a021fb0a875fc51f91948d6",
                "extracted_price": NaN,
                "reasons_not_to_buy": [
                    "Price information not available",
                    "No reviews available"
                ],
                "product_amount": "45 fl oz",
                "link": "https://www.google.com/shopping/product/6966355711229922688?hl=en&prds=oid:15783390977751551970,pid:3435914491712780582&sts=9&lsf=seller:253032654,store:10849949268498103315,s:h",
                "tag": "None",
                "description": "N/A",
                "extracted_product_reviews": -1.0,
                "price": 4.0,
                "product_reviews": 216.0,
                "reasons_to_buy": [
                    "Versatile multi-surface cleaner",
                    "Fresh scent"
                ],
                "extracted_product_rating": -1.0,
                "store": "Family Dollar",
                "title": "Mr. Clean Cleaner, Fresh, Multi-Surface - 45 fl oz",
                "score": 0.825465083
            },
            {
                "product_rating": "Not Found",
                "distance": "34.0 miles",
                "badge": "None",
                "stock_information": "In Stock",
                "status": "unprocessed",
                "store_address": "1608 Georgetown Road, Danville",
                "hours": "Today: 9:00 AM - 9:00 PM",
                "product_id": "497b6ce4-11a7-408b-8ca6-dee64db53ac0",
                "discount": -1.0,
                "old_price": -1.0,
                "value_per_unit": "N/A",
                "extracted_availability": true,
                "positive_reviews": [],
                "delivery_options": "Not Found",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRaNUX080wjNq18--7vEUAPaemET5EQvBDIFhrJUNXdgMzTwtXD8wb-0_Q7_OywMtT7PGp_wjaxFiL22-LHvZ3was03vzqyggSqyD8l18bosyHS4jAAu7wC&usqp=CAE",
                "negative_reviews": [],
                "extensions": [],
                "store_rating": -1.0,
                "store_reviews": -1.0,
                "product_hash": "8547a68aee281c271b7cee0d6ec77542e07109c8a9e73a5decfedfebbcf82c74",
                "extracted_price": 1.3,
                "reasons_not_to_buy": [
                    "Not recommended for glass or painted surfaces",
                    "May cause eye irritation and prolonged skin contact"
                ],
                "product_amount": "1 sponge",
                "link": "https://www.google.com/shopping/product/7977946310737249575?hl&prds=oid:13115667631068319650,pid:4847819210778600188&sts=2&lsf=seller:253032654,store:9128397350892905036,s:h",
                "tag": "None",
                "description": "Effective cleaning in a convenient, disposable sponge. Easily removes ground-in dirt, dust, and grime. Gives a natural matte finish. Great for your car's dash, vinyl, fabric, carpet, consoles, leather, and more.",
                "extracted_product_reviews": -1.0,
                "price": 1.3,
                "product_reviews": "Not Found",
                "reasons_to_buy": [
                    "Convenient and disposable sponge for easy cleaning",
                    "Effective in removing ground-in dirt and grime"
                ],
                "extracted_product_rating": -1.0,
                "store": "Family Dollar",
                "title": "Armor All Cleaning Sponge",
                "score": 0.825406849
            },
            {
                "product_rating": "Not Found",
                "distance": "15.7 miles",
                "badge": "None",
                "stock_information": "In Stock",
                "status": "unprocessed",
                "store_address": "1227 E Grove Ave, Rantoul",
                "hours": "Today: 9:00 AM - 10:00 PM",
                "product_id": "394fba83-64f4-4a2c-90a7-e9d9024f8e4e",
                "discount": -1.0,
                "old_price": -1.0,
                "value_per_unit": "N/A",
                "extracted_availability": true,
                "positive_reviews": [],
                "delivery_options": "Not Found",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRaNUX080wjNq18--7vEUAPaemET5EQvBDIFhrJUNXdgMzTwtXD8wb-0_Q7_OywMtT7PGp_wjaxFiL22-LHvZ3was03vzqyggSqyD8l18bosyHS4jAAu7wC&usqp=CAE",
                "negative_reviews": [],
                "extensions": [],
                "store_rating": -1.0,
                "store_reviews": -1.0,
                "product_hash": "8530ae655ffba1e715d137a170a7ea3c8527eb5ea40f8e68878a60374e6b2c64",
                "extracted_price": 1.25,
                "reasons_not_to_buy": [
                    "Not recommended for glass or painted surfaces",
                    "May cause eye irritation and should be kept out of reach of children"
                ],
                "product_amount": "1 unit",
                "link": "https://www.google.com/shopping/product/7977946310737249575?hl&prds=oid:13115667631068319650,pid:4847819210778600188&sts=2&lsf=seller:253032654,store:10849949268498103315,s:h",
                "tag": "None",
                "description": "Effective cleaning in a convenient, disposable sponge. Easily removes ground-in dirt, dust, and grime. Gives a natural matte finish. Great for your car's dash, vinyl, fabric, carpet, consoles, leather, and more.",
                "extracted_product_reviews": -1.0,
                "price": 1.25,
                "product_reviews": "Not Found",
                "reasons_to_buy": [
                    "Convenient and disposable sponge for easy cleaning",
                    "Effective in removing ground-in dirt and grime"
                ],
                "extracted_product_rating": -1.0,
                "store": "Family Dollar",
                "title": "Armor All Cleaning Sponge",
                "score": 0.822964907
            },
            {
                "product_rating": 4.6,
                "distance": 34.0,
                "badge": "None",
                "stock_information": "34.0 mi \\u00b7 In stock \\u00b7 Free 30-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "hours": "Not Found",
                "product_id": "59aa2c9d-2b83-4423-82da-e228fe059ff6",
                "discount": -1.0,
                "old_price": -1.0,
                "value_per_unit": "$0.08/oz",
                "extracted_availability": true,
                "positive_reviews": [],
                "delivery_options": "34.0 mi \\u00b7 In stock \\u00b7 Free 30-day returns",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSyVG7V6biEcv2OMJYAfQzLVI2R6ZMQCzhMOL1iQF8tcuwYvH5FyYbG7imiPU0&usqp=CAE",
                "negative_reviews": [],
                "extensions": [
                    "Degreaser",
                    "Spray",
                    "$0.72 below typical",
                    "LOW PRICE"
                ],
                "store_rating": -1.0,
                "store_reviews": -1.0,
                "product_hash": "22d89b6f40465435a1b0d4f3889366bdf784134915fcd9770ffc36e104ad505e",
                "extracted_price": 2.5,
                "reasons_not_to_buy": [
                    "No information about savings or discounts",
                    "Limited availability in certain locations"
                ],
                "product_amount": "32 fl oz",
                "link": "https://www.google.com/shopping/product/4523586226318597886?hl=en&prds=oid:9696008575886343746,pid:94956817837142668&sts=9&lsf=seller:253032654,store:9128397350892905036,s:h",
                "tag": "LOW PRICE",
                "description": "Fast cleaning of most washable surfaces. Removes stubborn soils such as grease, crayons, pencil and heel marks. Works on countertops, sinks, walls, ceramic tiles, floors and bathtubs. Pleasant fragrance.",
                "extracted_product_reviews": -1.0,
                "price": 2.5,
                "product_reviews": 980.0,
                "reasons_to_buy": [
                    "Effective in removing stubborn stains and soils",
                    "Versatile, can be used on various surfaces"
                ],
                "extracted_product_rating": -1.0,
                "store": "Family Dollar",
                "title": "Fantastik Scrubbing Bubbles Heavy Duty All Purpose Cleaner - 32 oz bottle",
                "score": 0.822907865
            }
        ],
        "sorted_by_price": [
            {
                "product_rating": "Not Found",
                "distance": "15.7 miles",
                "badge": "None",
                "stock_information": "In Stock",
                "status": "unprocessed",
                "store_address": "1227 E Grove Ave, Rantoul",
                "hours": "Today: 9:00 AM - 10:00 PM",
                "product_id": "394fba83-64f4-4a2c-90a7-e9d9024f8e4e",
                "discount": -1.0,
                "old_price": -1.0,
                "value_per_unit": "N/A",
                "extracted_availability": true,
                "positive_reviews": [],
                "delivery_options": "Not Found",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRaNUX080wjNq18--7vEUAPaemET5EQvBDIFhrJUNXdgMzTwtXD8wb-0_Q7_OywMtT7PGp_wjaxFiL22-LHvZ3was03vzqyggSqyD8l18bosyHS4jAAu7wC&usqp=CAE",
                "negative_reviews": [],
                "extensions": [],
                "store_rating": -1.0,
                "store_reviews": -1.0,
                "product_hash": "8530ae655ffba1e715d137a170a7ea3c8527eb5ea40f8e68878a60374e6b2c64",
                "extracted_price": 1.25,
                "reasons_not_to_buy": [
                    "Not recommended for glass or painted surfaces",
                    "May cause eye irritation and should be kept out of reach of children"
                ],
                "product_amount": "1 unit",
                "link": "https://www.google.com/shopping/product/7977946310737249575?hl&prds=oid:13115667631068319650,pid:4847819210778600188&sts=2&lsf=seller:253032654,store:10849949268498103315,s:h",
                "tag": "None",
                "description": "Effective cleaning in a convenient, disposable sponge. Easily removes ground-in dirt, dust, and grime. Gives a natural matte finish. Great for your car's dash, vinyl, fabric, carpet, consoles, leather, and more.",
                "extracted_product_reviews": -1.0,
                "price": 1.25,
                "product_reviews": "Not Found",
                "reasons_to_buy": [
                    "Convenient and disposable sponge for easy cleaning",
                    "Effective in removing ground-in dirt and grime"
                ],
                "extracted_product_rating": -1.0,
                "store": "Family Dollar",
                "title": "Armor All Cleaning Sponge",
                "score": 0.822964907
            },
            {
                "product_rating": "Not Found",
                "distance": "34.0 miles",
                "badge": "None",
                "stock_information": "In Stock",
                "status": "unprocessed",
                "store_address": "1608 Georgetown Road, Danville",
                "hours": "Today: 9:00 AM - 9:00 PM",
                "product_id": "497b6ce4-11a7-408b-8ca6-dee64db53ac0",
                "discount": -1.0,
                "old_price": -1.0,
                "value_per_unit": "N/A",
                "extracted_availability": true,
                "positive_reviews": [],
                "delivery_options": "Not Found",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRaNUX080wjNq18--7vEUAPaemET5EQvBDIFhrJUNXdgMzTwtXD8wb-0_Q7_OywMtT7PGp_wjaxFiL22-LHvZ3was03vzqyggSqyD8l18bosyHS4jAAu7wC&usqp=CAE",
                "negative_reviews": [],
                "extensions": [],
                "store_rating": -1.0,
                "store_reviews": -1.0,
                "product_hash": "8547a68aee281c271b7cee0d6ec77542e07109c8a9e73a5decfedfebbcf82c74",
                "extracted_price": 1.3,
                "reasons_not_to_buy": [
                    "Not recommended for glass or painted surfaces",
                    "May cause eye irritation and prolonged skin contact"
                ],
                "product_amount": "1 sponge",
                "link": "https://www.google.com/shopping/product/7977946310737249575?hl&prds=oid:13115667631068319650,pid:4847819210778600188&sts=2&lsf=seller:253032654,store:9128397350892905036,s:h",
                "tag": "None",
                "description": "Effective cleaning in a convenient, disposable sponge. Easily removes ground-in dirt, dust, and grime. Gives a natural matte finish. Great for your car's dash, vinyl, fabric, carpet, consoles, leather, and more.",
                "extracted_product_reviews": -1.0,
                "price": 1.3,
                "product_reviews": "Not Found",
                "reasons_to_buy": [
                    "Convenient and disposable sponge for easy cleaning",
                    "Effective in removing ground-in dirt and grime"
                ],
                "extracted_product_rating": -1.0,
                "store": "Family Dollar",
                "title": "Armor All Cleaning Sponge",
                "score": 0.825406849
            },
            {
                "product_rating": 4.6,
                "distance": 34.0,
                "badge": "None",
                "stock_information": "34.0 mi \\u00b7 In stock \\u00b7 Free 30-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "hours": "Not Found",
                "product_id": "59aa2c9d-2b83-4423-82da-e228fe059ff6",
                "discount": -1.0,
                "old_price": -1.0,
                "value_per_unit": "$0.08/oz",
                "extracted_availability": true,
                "positive_reviews": [],
                "delivery_options": "34.0 mi \\u00b7 In stock \\u00b7 Free 30-day returns",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSyVG7V6biEcv2OMJYAfQzLVI2R6ZMQCzhMOL1iQF8tcuwYvH5FyYbG7imiPU0&usqp=CAE",
                "negative_reviews": [],
                "extensions": [
                    "Degreaser",
                    "Spray",
                    "$0.72 below typical",
                    "LOW PRICE"
                ],
                "store_rating": -1.0,
                "store_reviews": -1.0,
                "product_hash": "22d89b6f40465435a1b0d4f3889366bdf784134915fcd9770ffc36e104ad505e",
                "extracted_price": 2.5,
                "reasons_not_to_buy": [
                    "No information about savings or discounts",
                    "Limited availability in certain locations"
                ],
                "product_amount": "32 fl oz",
                "link": "https://www.google.com/shopping/product/4523586226318597886?hl=en&prds=oid:9696008575886343746,pid:94956817837142668&sts=9&lsf=seller:253032654,store:9128397350892905036,s:h",
                "tag": "LOW PRICE",
                "description": "Fast cleaning of most washable surfaces. Removes stubborn soils such as grease, crayons, pencil and heel marks. Works on countertops, sinks, walls, ceramic tiles, floors and bathtubs. Pleasant fragrance.",
                "extracted_product_reviews": -1.0,
                "price": 2.5,
                "product_reviews": 980.0,
                "reasons_to_buy": [
                    "Effective in removing stubborn stains and soils",
                    "Versatile, can be used on various surfaces"
                ],
                "extracted_product_rating": -1.0,
                "store": "Family Dollar",
                "title": "Fantastik Scrubbing Bubbles Heavy Duty All Purpose Cleaner - 32 oz bottle",
                "score": 0.822907865
            },
            {
                "product_rating": "Not Found",
                "distance": "15.7 miles",
                "badge": "None",
                "stock_information": "In Stock",
                "status": "unprocessed",
                "store_address": "1227 E Grove Ave, Rantoul",
                "hours": "Today: 9:00 AM - 10:00 PM",
                "product_id": "7dd7cab1-2a21-4827-9511-a49daf228491",
                "discount": -1.0,
                "old_price": -1.0,
                "value_per_unit": "$0.098/oz",
                "extracted_availability": true,
                "positive_reviews": [],
                "delivery_options": "Not Found",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTNjX_zRHExmilVWhxuMnpRHFjvrogglT-Hil1Ii5CIj6znmPxAkrmpQxsUpZnIut1D6_1EAF3r0mCdD0U9WZblSrVVywOR9LsPmImv1Zw&usqp=CAE",
                "negative_reviews": [],
                "extensions": [],
                "store_rating": -1.0,
                "store_reviews": -1.0,
                "product_hash": "8091291142b0a3071a63e154f82000b27f72520a142924633188b5b853958452",
                "extracted_price": 2.75,
                "reasons_not_to_buy": [
                    "No savings or promotional offers mentioned",
                    "No information about certifications or listings"
                ],
                "product_amount": "28 fl oz",
                "link": "https://www.google.com/shopping/product/9581373145482938617?hl&prds=oid:11091789336316009600,pid:766997163069631063&sts=2&lsf=seller:253032654,store:10849949268498103315,s:h",
                "tag": "None",
                "description": "Removes soils with ease. Provides protection against stains in sinks and toilets. Formula leaves a fresh scent.",
                "extracted_product_reviews": -1.0,
                "price": 2.75,
                "product_reviews": "Not Found",
                "reasons_to_buy": [
                    "Effective in removing soils and stains",
                    "Leaves a fresh scent"
                ],
                "extracted_product_rating": -1.0,
                "store": "Family Dollar",
                "title": "Mr. Clean Antibacterial Multi-Surface Cleaner, Summer Citrus - 28 oz",
                "score": 0.827153683
            },
            {
                "product_rating": 4.8,
                "distance": 15.7,
                "badge": "None",
                "stock_information": "15.7 mi \\u00b7 In stock \\u00b7 Free 30-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "hours": "Not Found",
                "product_id": "0613eaa5-46d3-4e16-8eac-533370851be9",
                "discount": -1.0,
                "old_price": -1.0,
                "value_per_unit": "$0.09/fl oz",
                "extracted_availability": false,
                "positive_reviews": [],
                "delivery_options": "15.7 mi \\u00b7 In stock \\u00b7 Free 30-day returns",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRdJOdGmJGhWxWvG7b4a07LeOlrquhXt0H1VHAiyWanmE8360tCrwnHEVVsaj5VDesMEK2Gxaze&usqp=CAE",
                "negative_reviews": [],
                "extensions": [
                    "Concentrate"
                ],
                "store_rating": -1.0,
                "store_reviews": -1.0,
                "product_hash": "9a3755d33425e00cbbf6c9c41a5993a5ab89c27c8a021fb0a875fc51f91948d6",
                "extracted_price": NaN,
                "reasons_not_to_buy": [
                    "Price information not available",
                    "No reviews available"
                ],
                "product_amount": "45 fl oz",
                "link": "https://www.google.com/shopping/product/6966355711229922688?hl=en&prds=oid:15783390977751551970,pid:3435914491712780582&sts=9&lsf=seller:253032654,store:10849949268498103315,s:h",
                "tag": "None",
                "description": "N/A",
                "extracted_product_reviews": -1.0,
                "price": 4.0,
                "product_reviews": 216.0,
                "reasons_to_buy": [
                    "Versatile multi-surface cleaner",
                    "Fresh scent"
                ],
                "extracted_product_rating": -1.0,
                "store": "Family Dollar",
                "title": "Mr. Clean Cleaner, Fresh, Multi-Surface - 45 fl oz",
                "score": 0.825465083
            }
        ]
    },
    "Lowe's": {
        "sorted_by_score": [
            {
                "product_rating": 4.2,
                "distance": 3.5,
                "extracted_title": "Dremel Versa Power Cleaner Kit PC10-01",
                "badge": "None",
                "stock_information": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "reviews": [
                    "Tough cleaning jobs made easy with the Dremel Versa!",
                    "Compact and powerful tool for various cleaning tasks."
                ],
                "hours": "Not Found",
                "product_id": "5508994e-908c-47cd-8975-682fef43fc36",
                "discount": 3.0,
                "old_price": -1.0,
                "extracted_availability": true,
                "delivery_options": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "savings": [
                    "5% savings on eligible purchases every day"
                ],
                "thumbnail": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSKUxXZlcpSs5Oiu5jWUiDKwvi6K4bs8FdSPsYE50gJo2Z1_mZJPEQLgqR_y5iuwxG_j1Vc_GckA5UyznmZC11yvqOHl0g-M8Adn4E42-anJznaRfZCw-KkXg&usqp=CAE",
                "extensions": [
                    "CURBSIDE"
                ],
                "store_rating": 4.1,
                "store_reviews": 381.0,
                "product_hash": "35c0a532d88bc1c70fb800b97be059c6addb5618b07a322166298c3a89a2fe1c",
                "extracted_price": 59.99,
                "product_amount": "N/A",
                "link": "https://www.lowes.com/pd/Dremel-Versa-Micro-USB-2-5-in-Lithium-Ion-Li-ion-Power-Cleaner/1000422249?store_code=80",
                "tag": "CURBSIDE",
                "description": "Tough cleaning jobs are a thing of the past with the powerful and versatile Dremel Versa. High-speed scrubbing, in a compact size, is ideal for tackling soap scum, baked-on food, difficult grease, dirt, and much more. The Lithium-Ion battery charges fast and is perfect for indoor and outdoor, dry and wet uses. The lightweight and compact design is ideal for single-hand use and to tackle hard-to-reach places. Accessories changes are fast with the hook and loop interface. Switch from tile to glass, or upholstery to metal in no time, and use the Dremel Versa with or without water and cleaner based on the application.",
                "extracted_product_reviews": 423.0,
                "price": 59.99,
                "product_reviews": 331.0,
                "extracted_product_rating": 4.1,
                "store": "Lowe's",
                "title": "Dremel Versa Power Cleaner Kit PC10-01",
                "value_per_unit": NaN,
                "positive_reviews": NaN,
                "negative_reviews": NaN,
                "reasons_not_to_buy": NaN,
                "reasons_to_buy": NaN,
                "score": 0.828638375
            },
            {
                "product_rating": 4.6,
                "distance": 3.5,
                "extracted_title": "Simple Green All-Purpose Cleaner - 32 fl oz bottle",
                "badge": "None",
                "stock_information": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "reviews": [
                    "I love using Simple Green All-Purpose Cleaner. It works great on all surfaces and leaves a fresh scent. Highly recommended!",
                    "This cleaner is amazing! It removes tough stains and grease with ease. I've been using it for years and it never disappoints.",
                    "Simple Green All-Purpose Cleaner is my go-to cleaner for everything. It's safe to use and leaves my surfaces sparkling clean.",
                    "I purchased this cleaner based on the positive reviews and I'm glad I did. It's effective and affordable. Will buy again!"
                ],
                "hours": "Not Found",
                "product_id": "59a99aec-b953-471f-ad85-aade049aca49",
                "discount": 0.0,
                "old_price": -1.0,
                "extracted_availability": true,
                "delivery_options": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "savings": null,
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQxMuRK2CilYT-Frv55MrelWKZeev8_rg3tgBapSkg4814HOuCCUdAK1g-HzUDIY8gLDPYqOtvd-RCFdWxB6-vnHq7MZGKzqLQYviMb-GOZ6-Aj_f-7qXKYAw&usqp=CAE",
                "extensions": [
                    "Stain Remover",
                    "Spray",
                    "CURBSIDE"
                ],
                "store_rating": 4.1,
                "store_reviews": 381.0,
                "product_hash": "5ce16b1b154dbeef08231ace9d7db08a95c150ef5ead87cc16cfa288aae01e36",
                "extracted_price": 5.78,
                "product_amount": "32 fl oz",
                "link": "https://www.lowes.com/pd/Simple-Green-32-fl-oz-Sassafras-Liquid-All-Purpose-Cleaner/50091978?store_code=80",
                "tag": "CURBSIDE",
                "description": "Simple Green All-Purpose Cleaner is a powerful cleaner and degreaser designed for effective and environmentally safer use on all washable surfaces. The concentrated formula easily removes tough dirt and grime without harmful chemicals. It can be used full-strength for heavy messes or diluted with water for daily cleaning. This versatile cleaner can replace multiple harsh cleaners, making clean-up simple and safer. It has a refreshing sassafras scent and is readily biodegradable. Backed by a 100% money-back guarantee.",
                "extracted_product_reviews": 828.0,
                "price": 5.78,
                "product_reviews": 340.0,
                "extracted_product_rating": 4.8,
                "store": "Lowe's",
                "title": "Simple Green All-Purpose Cleaner - 32 fl oz bottle",
                "value_per_unit": "$0.18/fl oz",
                "positive_reviews": NaN,
                "negative_reviews": NaN,
                "reasons_not_to_buy": NaN,
                "reasons_to_buy": NaN,
                "score": 0.827721715
            },
            {
                "product_rating": 4.7,
                "distance": 3.5,
                "extracted_title": "Method All Purpose Surface Cleaner - Lavender - 28 oz",
                "badge": "None",
                "stock_information": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "reviews": [
                    "Great cleaner, leaves a fresh scent.",
                    "Effective on various surfaces.",
                    "Love the lavender fragrance."
                ],
                "hours": "Not Found",
                "product_id": "737c2f41-9186-4779-95f1-9f3ea8e1b67f",
                "discount": 0.0,
                "old_price": -1.0,
                "extracted_availability": true,
                "delivery_options": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "savings": [
                    "Free Shipping and 5% off eligible orders"
                ],
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTML0wFj2Vw_VbWXFqLjIku_W0QI6OiEHqfSYAYCo5iQ3XGqwUX9ODEnPuj3ZnKuZMik3m1I6XNHQSLy_hHCOdS-5j8Eqt305qLJ_8_Tws&usqp=CAE",
                "extensions": [
                    "Spray",
                    "CURBSIDE"
                ],
                "store_rating": 4.1,
                "store_reviews": 381.0,
                "product_hash": "4ab5373bb34db4b5a156da6a0aa9b688427787eca77d46c2ed42633079aae3e1",
                "extracted_price": 4.48,
                "product_amount": "28 fl oz",
                "link": "https://www.lowes.com/pd/method-28-fl-oz-Lavender-Liquid-All-Purpose-Cleaner/5013299679?store_code=80",
                "tag": "CURBSIDE",
                "description": "This all-purpose surface cleaner spray puts the hurt on dirt. It has a biodegradable formula with plant-based cleaning power that cuts through grease and grime. It can be used on most non-porous surfaces including counters, tile, stone, wood, and glass. The scent of lavender adds a pleasant aroma to your cleaning routine. The bottle is made with 100% recycled plastic (PCR).",
                "extracted_product_reviews": 78.0,
                "price": 4.48,
                "product_reviews": 17902.0,
                "extracted_product_rating": 4.8,
                "store": "Lowe's",
                "title": "Method All Purpose Surface Cleaner - Lavender - 28 oz",
                "value_per_unit": "$0.16/fl oz",
                "positive_reviews": NaN,
                "negative_reviews": NaN,
                "reasons_not_to_buy": NaN,
                "reasons_to_buy": NaN,
                "score": 0.827507257
            },
            {
                "product_rating": 3.8,
                "distance": 38.2,
                "extracted_title": NaN,
                "badge": "None",
                "stock_information": "38.2 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "reviews": NaN,
                "hours": "Not Found",
                "product_id": "0bfbd2bb-3745-4704-b20c-8e1f3e06f200",
                "discount": -1.0,
                "old_price": -1.0,
                "extracted_availability": true,
                "delivery_options": "38.2 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTuw6CEj6FVbD15Rg7UT8X6uis-teDQLKGWPhloI9HxEcvW6boXiJoC8--9k4mJo73zVBr_piG7vybLEl7etUx4_CpL5FO40yVHXkK0nOZwmZGe_4oHL26e&usqp=CAE",
                "extensions": [
                    "CURBSIDE"
                ],
                "store_rating": 4.1,
                "store_reviews": 381.0,
                "product_hash": "05b414f5916016ff7979f8bd4ba24ef00fe51429f0fbeeb94575089a846cee6f",
                "extracted_price": 3.48,
                "product_amount": "32 fl oz",
                "link": "https://www.lowes.com/pd/Formula-88-32-oz-Degreaser/1000241521?store_code=245",
                "tag": "CURBSIDE",
                "description": "Whether you have stains at the shop, the garage or at home, you can always reach for Formula 88 32 oz. Cleaner and degreaser. It can be used on tiles, rugs, bathrooms, kitchens, cars, boats and driveways. The powerful formula is non-flammable, non-hazardous, and non-corrosive. It cleans engines, grills, lawnmowers, bikes, cars, boats, steel, aluminum, driveways, boats, bathrooms, and kitchens. The degreaser is biodegradable.",
                "extracted_product_reviews": 11.0,
                "price": 3.48,
                "product_reviews": 6.0,
                "extracted_product_rating": 3.6,
                "store": "Lowe's",
                "title": "Formula 88 Cleaner 32 fl oz Degreaser",
                "value_per_unit": "$0.11/fl oz",
                "positive_reviews": [
                    "Love this degreaser. I do a lot of engine work and repairs to my sailboat and this degreaser just cuts through the mess of oil and grease stains.",
                    "Gets the job done. Spray leave and it comes right off."
                ],
                "negative_reviews": [
                    "Had to use the whole bottle plus it didn\\u2019t get the job done.",
                    "Mixed customer reviews"
                ],
                "reasons_not_to_buy": [
                    "Mixed customer reviews",
                    "May require larger quantities for tough stains"
                ],
                "reasons_to_buy": [
                    "Powerful formula for effective cleaning",
                    "Versatile usage on various surfaces"
                ],
                "score": 0.825931132
            },
            {
                "product_rating": 4.9,
                "distance": 3.5,
                "extracted_title": "CRC QD 02130 Contact Cleaner, 11 oz Aerosol Can",
                "badge": "None",
                "stock_information": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "reviews": [
                    "I have been using this contact cleaner for years and it never disappoints. It cleans effectively and evaporates quickly. Highly recommended!",
                    "Great product! It does a fantastic job of cleaning electronic components. I have used it multiple times and it always delivers excellent results.",
                    "This contact cleaner is a must-have for anyone working with electronics. It removes dirt and grime easily and leaves no residue behind. Very satisfied with the performance.",
                    "I purchased this contact cleaner to clean the connectors on my audio equipment. It worked like a charm and restored the connections to their original condition. Very happy with the results."
                ],
                "hours": "Not Found",
                "product_id": "61602c48-3a29-4825-8aa4-834a57efb32d",
                "discount": 0.0,
                "old_price": -1.0,
                "extracted_availability": true,
                "delivery_options": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "savings": null,
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQul8DiXq6Y0z6lEuUEh1zUrx6nNokqxfhdTXFI-NyLTB5BfttrcYn28fiaW519BIQo7Kbni4nUqzsDq6TTNf8hHiOHFBSwmWx9BSGIrPhWqQpYWi6cNl2j&usqp=CAE",
                "extensions": [
                    "CURBSIDE"
                ],
                "store_rating": 4.1,
                "store_reviews": 381.0,
                "product_hash": "30ce1dcf6560c0ed6419302a4f25118496ff1979fb399db88d03f87ae482d4a3",
                "extracted_price": 10.28,
                "product_amount": "11 oz",
                "link": "https://www.lowes.com/pd/CRC-Contact-Cleaner/999964587?store_code=80",
                "tag": "CURBSIDE",
                "description": "A petroleum distillate and alcohol blended precision cleaner suited for sensitive electronics and electrical equipment. Suitable for cleaning sensitive electronics and electrical equipment. Evaporates quickly, leaves no residue and is safe to use on all plastics. Use where lower flashpoint cleaners are acceptable. NSF K2 registered.",
                "extracted_product_reviews": 127.0,
                "price": 10.28,
                "product_reviews": 73.0,
                "extracted_product_rating": 4.8,
                "store": "Lowe's",
                "title": "CRC QD 02130 Contact Cleaner, 11 oz Aerosol Can",
                "value_per_unit": "$0.93/oz",
                "positive_reviews": NaN,
                "negative_reviews": NaN,
                "reasons_not_to_buy": NaN,
                "reasons_to_buy": NaN,
                "score": 0.823605239
            }
        ],
        "sorted_by_price": [
            {
                "product_rating": 3.8,
                "distance": 38.2,
                "extracted_title": NaN,
                "badge": "None",
                "stock_information": "38.2 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "reviews": NaN,
                "hours": "Not Found",
                "product_id": "0bfbd2bb-3745-4704-b20c-8e1f3e06f200",
                "discount": -1.0,
                "old_price": -1.0,
                "extracted_availability": true,
                "delivery_options": "38.2 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "savings": "N/A",
                "thumbnail": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTuw6CEj6FVbD15Rg7UT8X6uis-teDQLKGWPhloI9HxEcvW6boXiJoC8--9k4mJo73zVBr_piG7vybLEl7etUx4_CpL5FO40yVHXkK0nOZwmZGe_4oHL26e&usqp=CAE",
                "extensions": [
                    "CURBSIDE"
                ],
                "store_rating": 4.1,
                "store_reviews": 381.0,
                "product_hash": "05b414f5916016ff7979f8bd4ba24ef00fe51429f0fbeeb94575089a846cee6f",
                "extracted_price": 3.48,
                "product_amount": "32 fl oz",
                "link": "https://www.lowes.com/pd/Formula-88-32-oz-Degreaser/1000241521?store_code=245",
                "tag": "CURBSIDE",
                "description": "Whether you have stains at the shop, the garage or at home, you can always reach for Formula 88 32 oz. Cleaner and degreaser. It can be used on tiles, rugs, bathrooms, kitchens, cars, boats and driveways. The powerful formula is non-flammable, non-hazardous, and non-corrosive. It cleans engines, grills, lawnmowers, bikes, cars, boats, steel, aluminum, driveways, boats, bathrooms, and kitchens. The degreaser is biodegradable.",
                "extracted_product_reviews": 11.0,
                "price": 3.48,
                "product_reviews": 6.0,
                "extracted_product_rating": 3.6,
                "store": "Lowe's",
                "title": "Formula 88 Cleaner 32 fl oz Degreaser",
                "value_per_unit": "$0.11/fl oz",
                "positive_reviews": [
                    "Love this degreaser. I do a lot of engine work and repairs to my sailboat and this degreaser just cuts through the mess of oil and grease stains.",
                    "Gets the job done. Spray leave and it comes right off."
                ],
                "negative_reviews": [
                    "Had to use the whole bottle plus it didn\\u2019t get the job done.",
                    "Mixed customer reviews"
                ],
                "reasons_not_to_buy": [
                    "Mixed customer reviews",
                    "May require larger quantities for tough stains"
                ],
                "reasons_to_buy": [
                    "Powerful formula for effective cleaning",
                    "Versatile usage on various surfaces"
                ],
                "score": 0.825931132
            },
            {
                "product_rating": 4.7,
                "distance": 3.5,
                "extracted_title": "Method All Purpose Surface Cleaner - Lavender - 28 oz",
                "badge": "None",
                "stock_information": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "reviews": [
                    "Great cleaner, leaves a fresh scent.",
                    "Effective on various surfaces.",
                    "Love the lavender fragrance."
                ],
                "hours": "Not Found",
                "product_id": "737c2f41-9186-4779-95f1-9f3ea8e1b67f",
                "discount": 0.0,
                "old_price": -1.0,
                "extracted_availability": true,
                "delivery_options": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "savings": [
                    "Free Shipping and 5% off eligible orders"
                ],
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTML0wFj2Vw_VbWXFqLjIku_W0QI6OiEHqfSYAYCo5iQ3XGqwUX9ODEnPuj3ZnKuZMik3m1I6XNHQSLy_hHCOdS-5j8Eqt305qLJ_8_Tws&usqp=CAE",
                "extensions": [
                    "Spray",
                    "CURBSIDE"
                ],
                "store_rating": 4.1,
                "store_reviews": 381.0,
                "product_hash": "4ab5373bb34db4b5a156da6a0aa9b688427787eca77d46c2ed42633079aae3e1",
                "extracted_price": 4.48,
                "product_amount": "28 fl oz",
                "link": "https://www.lowes.com/pd/method-28-fl-oz-Lavender-Liquid-All-Purpose-Cleaner/5013299679?store_code=80",
                "tag": "CURBSIDE",
                "description": "This all-purpose surface cleaner spray puts the hurt on dirt. It has a biodegradable formula with plant-based cleaning power that cuts through grease and grime. It can be used on most non-porous surfaces including counters, tile, stone, wood, and glass. The scent of lavender adds a pleasant aroma to your cleaning routine. The bottle is made with 100% recycled plastic (PCR).",
                "extracted_product_reviews": 78.0,
                "price": 4.48,
                "product_reviews": 17902.0,
                "extracted_product_rating": 4.8,
                "store": "Lowe's",
                "title": "Method All Purpose Surface Cleaner - Lavender - 28 oz",
                "value_per_unit": "$0.16/fl oz",
                "positive_reviews": NaN,
                "negative_reviews": NaN,
                "reasons_not_to_buy": NaN,
                "reasons_to_buy": NaN,
                "score": 0.827507257
            },
            {
                "product_rating": 4.6,
                "distance": 3.5,
                "extracted_title": "Simple Green All-Purpose Cleaner - 32 fl oz bottle",
                "badge": "None",
                "stock_information": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "reviews": [
                    "I love using Simple Green All-Purpose Cleaner. It works great on all surfaces and leaves a fresh scent. Highly recommended!",
                    "This cleaner is amazing! It removes tough stains and grease with ease. I've been using it for years and it never disappoints.",
                    "Simple Green All-Purpose Cleaner is my go-to cleaner for everything. It's safe to use and leaves my surfaces sparkling clean.",
                    "I purchased this cleaner based on the positive reviews and I'm glad I did. It's effective and affordable. Will buy again!"
                ],
                "hours": "Not Found",
                "product_id": "59a99aec-b953-471f-ad85-aade049aca49",
                "discount": 0.0,
                "old_price": -1.0,
                "extracted_availability": true,
                "delivery_options": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "savings": null,
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQxMuRK2CilYT-Frv55MrelWKZeev8_rg3tgBapSkg4814HOuCCUdAK1g-HzUDIY8gLDPYqOtvd-RCFdWxB6-vnHq7MZGKzqLQYviMb-GOZ6-Aj_f-7qXKYAw&usqp=CAE",
                "extensions": [
                    "Stain Remover",
                    "Spray",
                    "CURBSIDE"
                ],
                "store_rating": 4.1,
                "store_reviews": 381.0,
                "product_hash": "5ce16b1b154dbeef08231ace9d7db08a95c150ef5ead87cc16cfa288aae01e36",
                "extracted_price": 5.78,
                "product_amount": "32 fl oz",
                "link": "https://www.lowes.com/pd/Simple-Green-32-fl-oz-Sassafras-Liquid-All-Purpose-Cleaner/50091978?store_code=80",
                "tag": "CURBSIDE",
                "description": "Simple Green All-Purpose Cleaner is a powerful cleaner and degreaser designed for effective and environmentally safer use on all washable surfaces. The concentrated formula easily removes tough dirt and grime without harmful chemicals. It can be used full-strength for heavy messes or diluted with water for daily cleaning. This versatile cleaner can replace multiple harsh cleaners, making clean-up simple and safer. It has a refreshing sassafras scent and is readily biodegradable. Backed by a 100% money-back guarantee.",
                "extracted_product_reviews": 828.0,
                "price": 5.78,
                "product_reviews": 340.0,
                "extracted_product_rating": 4.8,
                "store": "Lowe's",
                "title": "Simple Green All-Purpose Cleaner - 32 fl oz bottle",
                "value_per_unit": "$0.18/fl oz",
                "positive_reviews": NaN,
                "negative_reviews": NaN,
                "reasons_not_to_buy": NaN,
                "reasons_to_buy": NaN,
                "score": 0.827721715
            },
            {
                "product_rating": 4.9,
                "distance": 3.5,
                "extracted_title": "CRC QD 02130 Contact Cleaner, 11 oz Aerosol Can",
                "badge": "None",
                "stock_information": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "reviews": [
                    "I have been using this contact cleaner for years and it never disappoints. It cleans effectively and evaporates quickly. Highly recommended!",
                    "Great product! It does a fantastic job of cleaning electronic components. I have used it multiple times and it always delivers excellent results.",
                    "This contact cleaner is a must-have for anyone working with electronics. It removes dirt and grime easily and leaves no residue behind. Very satisfied with the performance.",
                    "I purchased this contact cleaner to clean the connectors on my audio equipment. It worked like a charm and restored the connections to their original condition. Very happy with the results."
                ],
                "hours": "Not Found",
                "product_id": "61602c48-3a29-4825-8aa4-834a57efb32d",
                "discount": 0.0,
                "old_price": -1.0,
                "extracted_availability": true,
                "delivery_options": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "savings": null,
                "thumbnail": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQul8DiXq6Y0z6lEuUEh1zUrx6nNokqxfhdTXFI-NyLTB5BfttrcYn28fiaW519BIQo7Kbni4nUqzsDq6TTNf8hHiOHFBSwmWx9BSGIrPhWqQpYWi6cNl2j&usqp=CAE",
                "extensions": [
                    "CURBSIDE"
                ],
                "store_rating": 4.1,
                "store_reviews": 381.0,
                "product_hash": "30ce1dcf6560c0ed6419302a4f25118496ff1979fb399db88d03f87ae482d4a3",
                "extracted_price": 10.28,
                "product_amount": "11 oz",
                "link": "https://www.lowes.com/pd/CRC-Contact-Cleaner/999964587?store_code=80",
                "tag": "CURBSIDE",
                "description": "A petroleum distillate and alcohol blended precision cleaner suited for sensitive electronics and electrical equipment. Suitable for cleaning sensitive electronics and electrical equipment. Evaporates quickly, leaves no residue and is safe to use on all plastics. Use where lower flashpoint cleaners are acceptable. NSF K2 registered.",
                "extracted_product_reviews": 127.0,
                "price": 10.28,
                "product_reviews": 73.0,
                "extracted_product_rating": 4.8,
                "store": "Lowe's",
                "title": "CRC QD 02130 Contact Cleaner, 11 oz Aerosol Can",
                "value_per_unit": "$0.93/oz",
                "positive_reviews": NaN,
                "negative_reviews": NaN,
                "reasons_not_to_buy": NaN,
                "reasons_to_buy": NaN,
                "score": 0.823605239
            },
            {
                "product_rating": 4.2,
                "distance": 3.5,
                "extracted_title": "Dremel Versa Power Cleaner Kit PC10-01",
                "badge": "None",
                "stock_information": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "status": "unprocessed",
                "store_address": "Not Found",
                "reviews": [
                    "Tough cleaning jobs made easy with the Dremel Versa!",
                    "Compact and powerful tool for various cleaning tasks."
                ],
                "hours": "Not Found",
                "product_id": "5508994e-908c-47cd-8975-682fef43fc36",
                "discount": 3.0,
                "old_price": -1.0,
                "extracted_availability": true,
                "delivery_options": "3.5 mi \\u00b7 In stock \\u00b7 Free 90-day returns",
                "savings": [
                    "5% savings on eligible purchases every day"
                ],
                "thumbnail": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSKUxXZlcpSs5Oiu5jWUiDKwvi6K4bs8FdSPsYE50gJo2Z1_mZJPEQLgqR_y5iuwxG_j1Vc_GckA5UyznmZC11yvqOHl0g-M8Adn4E42-anJznaRfZCw-KkXg&usqp=CAE",
                "extensions": [
                    "CURBSIDE"
                ],
                "store_rating": 4.1,
                "store_reviews": 381.0,
                "product_hash": "35c0a532d88bc1c70fb800b97be059c6addb5618b07a322166298c3a89a2fe1c",
                "extracted_price": 59.99,
                "product_amount": "N/A",
                "link": "https://www.lowes.com/pd/Dremel-Versa-Micro-USB-2-5-in-Lithium-Ion-Li-ion-Power-Cleaner/1000422249?store_code=80",
                "tag": "CURBSIDE",
                "description": "Tough cleaning jobs are a thing of the past with the powerful and versatile Dremel Versa. High-speed scrubbing, in a compact size, is ideal for tackling soap scum, baked-on food, difficult grease, dirt, and much more. The Lithium-Ion battery charges fast and is perfect for indoor and outdoor, dry and wet uses. The lightweight and compact design is ideal for single-hand use and to tackle hard-to-reach places. Accessories changes are fast with the hook and loop interface. Switch from tile to glass, or upholstery to metal in no time, and use the Dremel Versa with or without water and cleaner based on the application.",
                "extracted_product_reviews": 423.0,
                "price": 59.99,
                "product_reviews": 331.0,
                "extracted_product_rating": 4.1,
                "store": "Lowe's",
                "title": "Dremel Versa Power Cleaner Kit PC10-01",
                "value_per_unit": NaN,
                "positive_reviews": NaN,
                "negative_reviews": NaN,
                "reasons_not_to_buy": NaN,
                "reasons_to_buy": NaN,
                "score": 0.828638375
            }
        ]
    }
}